---
title: "CICI Code"
author: "Yuanzhi Yu"
date: "2022/6/29"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(rstan)
library(gdata)
library(bayesplot)
library(MASS)
library(dplyr)
library(naniar)
library(Matrix)
library(knitr)
library(tictoc)
library(mice)
library(parallel)
library(truncnorm)
library(abind)
library(matrixcalc)
library(mvtnorm)
library(MCMCpack)
library(ggpubr) # for putting graphs on same plot
require(parallel) # one of the core R packages
require(doParallel)
library(foreach)
library(iterators)
library(ggfortify)
library(matrixStats)
library(kableExtra)
library(patchwork)
library(bootImpute)
library(tidyverse)
library(mice)
library(investr)
library(MASS)
library(readxl)
library(ggcorrplot)
library(nnet)
library(lme4)
library(gee)
library(geepack)
library(geeM)
library(ggcorrplot)
library(gridExtra)
library(ggthemr)
library(latex2exp)
library(scales)
library(grid)
library(gridExtra)
library(tidyverse)
library(ggpubr)
library(RColorBrewer)
library(data.table)
library(ggprism)
library(corrplot)
library(ggbreak)
library(AER)
library(MCMCglmm)
```

##### Generate data

```{r}
data_generate = function(true_x1, true_x2, true_x3, true_z, rhoxx, rhoxz, sigmaww.x, rhoww.x, p1, p2, p3){
  
  muxz <- c(0, 0, 0, 0) # Mean
  sigmaxz = matrix(c(1, 1*rhoxx, 1*rhoxx, 1*rhoxz, 
                     1*rhoxx, 1, 1*rhoxx, 1*rhoxz, 
                     1*rhoxx, 1*rhoxx, 1, 1*rhoxz, 
                     1*rhoxz, 1*rhoxz, 1*rhoxz, 1), 4, 4)
  
  sigmaxw <- matrix(c(sigmaww.x, sigmaww.x*rhoww.x, sigmaww.x*rhoww.x, 
                      sigmaww.x*rhoww.x,sigmaww.x, sigmaww.x*rhoww.x, 
                      sigmaww.x*rhoww.x, sigmaww.x*rhoww.x, sigmaww.x), 3, 3)
  df_xz_m = mvrnorm(n = 400, mu = muxz, Sigma = sigmaxz)
  
  #df_x = rbind(df_x_c, df_xz_m[,1:3])
  df_w = c()
  for(i in 1:400){
    muw = c((1.1* df_xz_m[i, 1]), (1.1 * df_xz_m[i, 2]), (1.1 * df_xz_m[i, 3]))
    df_w_a = mvrnorm(n = 1, mu = muw, Sigma = sigmaxw)
    df_w = rbind(df_w, df_w_a)
  }
  #zc = ifelse(df_xz_m[,4] >= 0, 1, 0)
  missing_data = cbind(w1 = df_w[,1],
                       w2 = df_w[,2],
                       w3 = df_w[,3],
                       x1 = df_xz_m[,1],
                       x2 = df_xz_m[,2],
                       x3 = df_xz_m[,3],
                       z = df_xz_m[,4], 
                       y = rnorm(400, mean = true_x1 * df_xz_m[,1] + 
                                   true_x2 * df_xz_m[,2] + 
                                   true_x3 * df_xz_m[,3] + 
                                   true_z * df_xz_m[,4], 1)) %>% as.matrix()
  c_data = missing_data
  
  l_data = c_data
  l_data1 = l_data[1:100,]
  l_data2 = l_data[101:400,]
  m_data2 = l_data[101:400,]
  
  
  pp = c(l_data2[order(l_data2[,1],decreasing=F)[p1],1],
         l_data2[order(l_data2[,2],decreasing=F)[p2],2],
         l_data2[order(l_data2[,3],decreasing=F)[p3],3])
  nn = c(l_data2[order(l_data2[,1],decreasing=F)[1],1],
         l_data2[order(l_data2[,2],decreasing=F)[1],2],
         l_data2[order(l_data2[,3],decreasing=F)[1],3])
  
  
  m_data2[which(l_data2[,1]<=pp[1]),1]= log(exp(pp[1])/sqrt(2))
  m_data2[which(l_data2[,2]<=pp[2]),2]= log(exp(pp[1])/sqrt(2))
  m_data2[which(l_data2[,3]<=pp[3]),3]= log(exp(pp[1])/sqrt(2))
  
  l_data2[which(l_data2[,1]<=pp[1]),1]= NA
  l_data2[which(l_data2[,2]<=pp[2]),2]= NA
  l_data2[which(l_data2[,3]<=pp[3]),3]= NA
  
  l_data = rbind(l_data1, l_data2)
  l_data[c(101:400),4:6] = NA
  l_data[1:100,7:8] = NA
  
  m_data = rbind(l_data1, m_data2)
  m_data[c(101:400),4:6] = NA
  m_data[1:100,7:8] = NA
  
  return(list(m_data = m_data, c_data = c_data, l_data = l_data, pp = pp, nn = nn))
}

#### set missingness rate as 10%, 10%, 10% in W of main study sample
set.seed(666)
dg = data_generate(1.2, 0.8, 0.4, 0.4, 0.3, 0.3, 0.25, 0, 30, 30, 30)
#### Upper bound and lower bound of W
pp = dg$pp
nn = dg$nn

#### External design with one calibration data
imp1 = dg$m_data %>% as.tibble()

#### External design with one calibration data with lod
imp2 = dg$l_data %>% as.tibble()

#### Complete data ("True" data)
c_data = dg$c_data %>% as.tibble()

```

##### Complete data ("True" data) 

```{r}
fit_c = lm(y[101:400]~ x1[101:400] + x2[101:400] + x3[101:400] + z[101:400],data=c_data)
cbind(fit_c$coefficients,fit_c %>% confint())
```



##### CICI

```{r}
bn = 2
ss = 666
predM = rbind(c(0,0,0,1,0,0,0,0), 
              c(0,0,0,0,1,0,0,0), 
              c(0,0,0,0,0,1,0,0),
              c(1,0,0,0,1,1,1,1), 
              c(0,1,0,1,0,1,1,1), 
              c(0,0,1,1,1,0,1,1), 
              c(0,0,0,1,1,1,0,1),
              c(0,0,0,1,1,1,1,0))


    impOnce <- function(inputData,M) {
      miceImps <- mice::mice(inputData, m=M, maxit = 20, print = F, method = "norm", predictorMatrix = predM, upper_bound = pp, type_c = colnames(imp2)) #, remove.collinear = FALSE
      imps <- vector("list", M)
      for (i in 1:M) {
        imps[[i]] <- mice::complete(miceImps,i)
      }
      imps
    }
    imps1 <- bootImpute(imp1, impOnce, nBoot=200, nImp = bn,seed=ss, M = bn) ### nboot = 200
    analyseImp <- function(inputData) {
      coef(lm(y[101:400]~ x1[101:400] + x2[101:400] + x3[101:400] + z[101:400],data=inputData))
    }
    result1 = bootImputeAnalyse(imps1, analyseImp)
    a_bm1 =  cbind(result1$ests, result1$ci) 
    a_bm1
```

##### CICI-LOD

```{r}
mice.impute.RUTR <- function(y, ry, type, x, wy = NULL, upper_bound, type_c,...){ 
  
  ### Choose upper bound for y
  '%ni%' <- Negate('%in%')
  upper_bound_y <- upper_bound[which(type_c %ni% attributes(type)$name)[1]]
  
  ### Data for tobit
  y1 = y
  y1[wy] = upper_bound_y - 1 
  dt = data.frame(y1, x)
  
  ### Tobit regression, Mu & Sigma
  utobit <- tobit(y1 ~ ., data = dt, left = upper_bound_y, dist = "gaussian")
  mu <- predict(utobit) 
  mu_u <- mu[wy] 
  sigma_u <- utobit$scale 
  
  ### Impute LOD
  lod = length(which(wy*1 == 1))
  imp_u = c()
  for(i in 1:lod){
    imp_u[i] = rtnorm(1, mean = mu_u[i],sd = sigma_u, upper = upper_bound_y)}
  
  return(imp_u)
}



    impOnce <- function(inputData,M) {
      miceImps <- mice::mice(inputData, m=M, maxit = 200, print = F, method = c("RUTR", "RUTR", "RUTR", "norm", "norm", "norm", "norm", "norm"), predictorMatrix = predM, upper_bound = pp, type_c = colnames(imp2)) #, remove.collinear = FALSE
      imps <- vector("list", M)
      for (i in 1:M) {
        imps[[i]] <- mice::complete(miceImps,i)
      }
      imps
    }
    imps2 <- bootImpute(imp2, impOnce, nBoot=200, nImp = bn,seed=ss, M = bn) 
    analyseImp <- function(inputData) {
      coef(lm(y[101:400]~ x1[101:400] + x2[101:400] + x3[101:400] + z[101:400],data=inputData))
    }
    result2 = bootImputeAnalyse(imps2, analyseImp)
    a_bm2 =  cbind(result2$ests, result2$ci)
```

